config/routes.rb
CmuEventRegistration::Application.routes.draw do
  resources :organizer_lists

  resources :events

  resources :locations

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer          not null, primary key
#  date         :datetime
#  name         :string(255)
#  description  :string(255)
#  capacity     :integer
#  organization :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#

class Event < ActiveRecord::Base
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  latitude   :float
#  longitude  :float
#  name       :string(255)
#  details    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Location < ActiveRecord::Base
end

app/models/organizer_list.rb
# == Schema Information
#
# Table name: organizer_lists
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class OrganizerList < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :name, :description, :capacity, :organization)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude, :name, :details)
    end
end

app/controllers/organizer_lists_controller.rb
class OrganizerListsController < ApplicationController
  before_action :set_organizer_list, only: [:show, :edit, :update, :destroy]

  # GET /organizer_lists
  # GET /organizer_lists.json
  def index
    @organizer_lists = OrganizerList.all
  end

  # GET /organizer_lists/1
  # GET /organizer_lists/1.json
  def show
  end

  # GET /organizer_lists/new
  def new
    @organizer_list = OrganizerList.new
  end

  # GET /organizer_lists/1/edit
  def edit
  end

  # POST /organizer_lists
  # POST /organizer_lists.json
  def create
    @organizer_list = OrganizerList.new(organizer_list_params)

    respond_to do |format|
      if @organizer_list.save
        format.html { redirect_to @organizer_list, notice: 'Organizer list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organizer_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @organizer_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizer_lists/1
  # PATCH/PUT /organizer_lists/1.json
  def update
    respond_to do |format|
      if @organizer_list.update(organizer_list_params)
        format.html { redirect_to @organizer_list, notice: 'Organizer list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organizer_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizer_lists/1
  # DELETE /organizer_lists/1.json
  def destroy
    @organizer_list.destroy
    respond_to do |format|
      format.html { redirect_to organizer_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organizer_list
      @organizer_list = OrganizerList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organizer_list_params
      params[:organizer_list]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/organizer_lists_helper.rb
module OrganizerListsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.datetime_select :date
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :capacity
    = f.number_field :capacity
  .field
    = f.label :organization
    = f.text_field :organization
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table
  %tr
    %th Date
    %th Name
    %th Description
    %th Capacity
    %th Organization
    %th
    %th
    %th

  - @events.each do |event|
    %tr
      %td= event.date
      %td= event.name
      %td= event.description
      %td= event.capacity
      %td= event.organization
      %td= link_to 'Show', event
      %td= link_to 'Edit', edit_event_path(event)
      %td= link_to 'Destroy', event, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @event.date
%p
  %b Name:
  = @event.name
%p
  %b Description:
  = @event.description
%p
  %b Capacity:
  = @event.capacity
%p
  %b Organization:
  = @event.organization

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmuEventRegistration</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.haml
= form_for @location do |f|
  - if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :details
    = f.text_field :details
  .actions
    = f.submit 'Save'

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Listing locations

%table
  %tr
    %th Latitude
    %th Longitude
    %th Name
    %th Details
    %th
    %th
    %th

  - @locations.each do |location|
    %tr
      %td= location.latitude
      %td= location.longitude
      %td= location.name
      %td= location.details
      %td= link_to 'Show', location
      %td= link_to 'Edit', edit_location_path(location)
      %td= link_to 'Destroy', location, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Latitude:
  = @location.latitude
%p
  %b Longitude:
  = @location.longitude
%p
  %b Name:
  = @location.name
%p
  %b Details:
  = @location.details

= link_to 'Edit', edit_location_path(@location)
\|
= link_to 'Back', locations_path

app/views/organizer_lists/_form.html.haml
= form_for @organizer_list do |f|
  - if @organizer_list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@organizer_list.errors.count, "error")} prohibited this organizer_list from being saved:"
      %ul
        - @organizer_list.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/organizer_lists/edit.html.haml
%h1 Editing organizer_list

= render 'form'

= link_to 'Show', @organizer_list
\|
= link_to 'Back', organizer_lists_path

app/views/organizer_lists/index.html.haml
%h1 Listing organizer_lists

%table
  %tr
    %th
    %th
    %th

  - @organizer_lists.each do |organizer_list|
    %tr
      %td= link_to 'Show', organizer_list
      %td= link_to 'Edit', edit_organizer_list_path(organizer_list)
      %td= link_to 'Destroy', organizer_list, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Organizer list', new_organizer_list_path

app/views/organizer_lists/new.html.haml
%h1 New organizer_list

= render 'form'

= link_to 'Back', organizer_lists_path

app/views/organizer_lists/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_organizer_list_path(@organizer_list)
\|
= link_to 'Back', organizer_lists_path